import sys
import logging
import argparse
import json
from pathlib import Path
from datetime import datetime
from typing import Optional

# Centralized SOC Config & New RAG Modules
try:
    import config
    from csv_to_incident import CSVToIncidentConverter
    from knowledge_base import fetch_expert_context  # NEW RAG BRIDGE
    from report_generator import IncidentReportGenerator
except ImportError as e:
    print(f"CRITICAL ERROR: Project structure invalid or missing dependencies: {e}")
    sys.exit(1)

# Configure professional logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger(__name__)

class UnifiedPipeline:
    def __init__(self, input_file: str, human_insight: str = "", model: Optional[str] = None):
        self.input_file = Path(input_file)
        self.human_insight = human_insight
        
        # Unique RUN ID: The 'Glue' for the Forensic Vault
        self.run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Use centralized vault path from config
        self.output_dir = config.OUTPUT_DIR
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def detect_input_type(self) -> str:
        if not self.input_file.exists():
            raise FileNotFoundError(f"Target file not found in vault: {self.input_file}")
        
        suffix = self.input_file.suffix.lower()
        if suffix == ".csv":
            return "csv"
        return "text"

    def run(self) -> bool:
        """Executes the synchronized Semantic + RAG investigation workflow."""
        logger.info("="*60)
        logger.info(f"SOC INVESTIGATION START | ID: {self.run_id}")
        logger.info(f"HARDWARE: GPU-Optimized Multi-Agent Flow")
        logger.info("="*60)
        
        try:
            input_type = self.detect_input_type()
            
            if input_type == "csv":
                return self._process_semantic_workflow()
            else:
                # If input is already text, we still pull RAG context for it
                logger.info("Direct Text Input Detected. Fetching Knowledge context...")
                rag_context = fetch_expert_context(str(self.input_file))
                return self._trigger_generator(str(self.input_file), rag_context)

        except Exception as e:
            logger.error(f"PIPELINE CRASHED: {e}")
            return False

    def _process_semantic_workflow(self) -> bool:
        """Handles Raw CSV -> JSON Truth Block -> RAG Enrichment -> AI Synthesis."""
        try:
            # PHASE 1: Semantic Extraction (Turn logs into structured JSON)
            converter = CSVToIncidentConverter(
                csv_file=str(self.input_file),
                human_insight=self.human_insight,
                run_id=self.run_id 
            )
            json_vault_path = converter.convert()
            
            if not json_vault_path:
                return False
                
            # PHASE 2: Intelligence Retrieval (RAG)
            # We load the JSON to get the 'mitre_query' generated by the Extractor
            with open(json_vault_path, 'r') as f:
                truth_block = json.load(f)
            
            search_query = truth_block.get("FINDINGS", {}).get("mitre_query", "security incident")
            logger.info(f"PHASE 2: Querying Knowledge Base for: '{search_query}'")
            
            rag_context = fetch_expert_context(search_query)

            # PHASE 3: Lead-Level AI Synthesis
            logger.info("PHASE 3: Generating Final Report via DeepSeek-R1")
            return self._trigger_generator(json_vault_path, rag_context)
            
        except Exception as e:
            logger.error(f"Semantic Workflow Failed: {e}")
            return False

    def _trigger_generator(self, incident_path: str, rag_context: str) -> bool:
        """Triggers the reasoning engine with synchronized RAG context."""
        try:
            generator = IncidentReportGenerator()
            return generator.generate_report(
                incident_path=incident_path, 
                rag_context=rag_context, 
                run_id=self.run_id
            )
        except Exception as e:
            logger.error(f"AI Generation Failed: {e}")
            return False

def main():
    parser = argparse.ArgumentParser(description="SOC Agent - GPU Semantic Pipeline")
    parser.add_argument("input_file", help="Path to logs (CSV) or Incident text (TXT)")
    parser.add_argument("--insight", default="", help="Analyst's primary investigative truth")
    
    args = parser.parse_args()
    
    pipeline = UnifiedPipeline(
        input_file=args.input_file,
        human_insight=args.insight
    )
    
    success = pipeline.run()
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()